![](files/images/cover_numpy.png)

 ![](files/images/rubber_duck.png)
 
 https://en.wikipedia.org/wiki/Rubber_duck_debugging

## Goal of the lecture

Learn 
* how to use of the objects provided by numpy
* how to read data from files and manipulate it
* how to integrate python with plotting
* and of course ...


* ... how to have fun with it ...

![](files/images/xkcd.png)

In [37]:
import antigravity

but don't get overly exicted

![](files/images/coding_drunk.png)

## Introduction (1): history
* Numerical Python: evolution
 * In origin, 2 different libraries Numeric and Numarray
 * They became NumPy (2006). All the features of the two original libraries (plus more..) converging in one library


## Introduction (2): why bother?
* NumPy offers efficient array storing and computation
* Python scientific libraries (i.e. scipy, matplotlib, pandas) make use of NumPy objects
* NumPy is the __de facto__ standard

### Introduction (3): what's inside the box

![](files/images/numpy_pkgs.png)

## Introduction (4)

* Default for this presentation (and for the standard documentation)

In [38]:
import numpy as np

## NumPy (main) objects

* NumPy provides two main objects:
 * __ndarray__;
 * __ufunc__;


## ndarray

* Like lists, tuples and sets, ndarrays are collection of items
```python
>>> my_array, type(my_array)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)
```

## ndarray/2

Examples:

In [39]:
a = np.array([1, 2, 3])  # try also: 
                         # b = np.array([[1.5, 2.2, 34.4], [2.3, 4, 6.5]])
                         # c = np.array(['lof', 'l', 'ga']) 
a

array([1, 2, 3])

In [40]:
c = np.array([2, 3, 'lof'])  # doesn't work asexpected
print(c)

['2' '3' 'lof']


## ndarray/3

* ndarray is a collection of __homogeneous__ items
 * Each item occupies the same number of bytes
* Items typically are numerical type...
* ... but an arbitrary __record__ of (non) numerical types can be used


## ndarray/4


`numpy/core/include/numpy/ndarrayobject.h`

<pre style="font-size:60%;"> 
typedef struct PyArrayObject {
char *data;            /* pointer to raw data buffer */ 
PyArray_Descr *descr;  /* Pointer to type structure */ 
int nd;                /* number of dimensions, also called ndim */
npy_intp *dimensions;  /* size in each dimension (shape) */
npy_intp *strides;     /* bytes to jump to get to the next element in each dimension */
PyObject *base;        /* This object should be decref'd upon deletion of array */ 
                       /* For views it points to the original array */ 
int flags;             /* Flags describing array */
} PyArrayObject;
</pre>

## ndarray: data

```C
char *data;  /* pointer to raw data buffer */ 
PyArray_Descr *descr;  /* pointer to type structure */
```

* `data` is just a pointer to bytes in memory
* `data` needs some sort of descriptor (dtype) to be interpreted


In [41]:
a = np.array([1, 2, 3])  # buffer of 12 bytes intepreted as 3 ints
a.dtype                  # int32 -> 32bits -> 4 bytes

dtype('int32')

In [42]:
b = a.astype(np.float)  # dtype('float64') 

## ndarray: some dtype types

![](files/images/dtypes.png)

## ndarray: dtype cont'ed

* the elements of `ndarrays` can be specified with a dtype object:


__numerical__
```python
>>> np.dtype(np.int32) # 32 are the bits used to 
dtype('np.int32')      # represent the integer  
                       # (4 bytes int) 
```
__strings__
```python
>>> np.dtype('S3') # mind the capital case here
                   # 3 means 3 bytes 
```
__both__
```python
>>> np.dtype([('f1', np.uint), ('f2', 'S3')])
dtype([('f1', '<u4'), ('f2', '|S3')])   # list of tuples
```

## Enough theory...

* Let's get our (dirty) hands on this new toy
* During this course, most of the things we learn will be used to solve an exercise
* It's about ...


![](files/images/break_bad.png)

## Exercise
* Rotate a molecule along the axes that diagonalize the moment of inertia tensor
* step by step guided solution through this course

![](files/images/mol.png)

## Exercise 1: dtype
Try to construct a dtype object to represent an atom in a 3d space. It should contain:
 * a string ('S3') to represent the symbol (i.e. Na, Cl, H, O)
 * an integer (np.int) for the atomic weight (i.e. 11, 17, 1)
 * 3 floats 64 bits (np.float64) for the cartesian coordinates

* Help needed? Try (after having imported numpy):
```
>>> help(np.dtype) (python)
>>> np.dtype? (ipython)
```

## Exercise 1: dtype
* Solution

In [43]:
dt = np.dtype([('symb','S3'),('PA',np.int), ('x',np.float64),('y',np.float64),('z',np.float64)]) 
print(dt)

[('symb', 'S3'), ('PA', '<i4'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8')]


## ndarray/5


`numpy/core/include/numpy/ndarrayobject.h`

<pre style="font-size:60%;">
typedef struct PyArrayObject {
char *data;            /* pointer to raw data buffer */ 
PyArray_Descr *descr;  /* Pointer to type structure */ 
int nd;                /* number of dimensions, also called ndim */
npy_intp *dimensions;  /* size in each dimension (shape) */
npy_intp *strides;     /* bytes to jump to get to the next element in each dimension */
PyObject *base;        /* This object should be decref'd upon deletion of array */ 
                       /* For views it points to the original array */ 
int flags;             /* Flags describing array */
} PyArrayObject;
</pre>

## ndarray: dimensions

```C
int nd;                /* number of dimensions, also called ndim */
 
npy_intp *dimensions;  /* size in each dimension */
``` 

In [44]:
b = np.array([[1,2], [3,4]])
b.ndim

2

In [45]:
b.shape

(2, 2)

In [46]:
b.shape = 1,4  # reshaping the array

## Creating arrays/1

__5 general mechanism__ to create arrays:

__(1)__ Conversion from other Python structures (e.g. lists, tuples): np.array function

In [47]:
list = [0,2,3,7]
a = np.array(list)
print(a, type(a))

[0 2 3 7] <class 'numpy.ndarray'>


In [48]:
b = np.array([list,list])  # l, m python lists
b = np.asarray(b)    # convert b to an array if b is, 
                     # i.e. a list; otherwise does nothing 

## Creating arrays/2
 
__(2)__ Intrinsic `NumPy` array creation functions

In [49]:
a_ = np.zeros(10)
print(a_)
b_ = np.ones((3,2))
print(b_)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [50]:
c_ = np.linspace(0,10,11)  # start, stop, npoints 
print(c_)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [51]:
d_ = np.arange(10)  # try also np.arange(1,10,2)
print(d_)

[0 1 2 3 4 5 6 7 8 9]


## Creating arrays/3
 
Try the shortcut: __np.r_ __



In [52]:
a = np.r_[0,1,2]  # ~ np.array
print(a)
a = np.r_[0:1:0.1]  # np.arange
print(a)
a = np.r_[0:2:20j]  # np.linspace
print(a)

[0 1 2]
[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]
[ 0.          0.10526316  0.21052632  0.31578947  0.42105263  0.52631579
  0.63157895  0.73684211  0.84210526  0.94736842  1.05263158  1.15789474
  1.26315789  1.36842105  1.47368421  1.57894737  1.68421053  1.78947368
  1.89473684  2.        ]


## Creating arrays/4

__(4)__ Reading arrays from disk, either from standard or custom formats (mind the __byte order!!__)

```
loadtxt, genfromtxt  # custom ASCII formats

fromfile()           # custom binary
<ndarray>.tofile()      

h5py, pytables    # binary standard formats 
netcdf-python 
```

 ## Creating arrays/5

Reading from ASCII text files
```
loadtxt(fname[, dtype=, comments=, ...])
```
Save an array to ASCII text file (auto recognizes if .gz)  
```
savetxt(fname, X[, fmt=, delimiter=])
```

* `loadtxt` is faster but less flexible
* `genfromtxt` runs two loops, the first reads all the lines (→strings), the second parses the line and converts each string to a data type
 * It has the advantage of taking into account missing data


## Exercise 2: creating array

1. Create a ndarray of 6x5 elements, all set to 1
```
>>> help(np.ones)
```

2. Reshape the array to 3x10

3. Download 'mol.xyz' from here and build a new array of atom dtype
```
>>> help(np.loadtxt)
```

## Exercise 2: creating array

1.
```python
>>> a = np.ones((6,5))
```
2.
```python
>>> a.shape = 3,10
```
3.
```python
>>> dt = np.dtype([('symb','|S3'),('PA',np.int), ('x',np.float64),('y',np.float64),('z',np.float64)]) 
>>> arr = np.loadtxt('mol.xyz',dtype=dt)
```

In [53]:
arr = np.loadtxt('data/mol.xyz', dtype=dt)
print(arr)

[(b'C', 12, -0.102, -0.301, -0.276) (b'C', 12, -0.024, -0.189, 1.125)
 (b'C', 12, 1.254, -0.165, 1.713) (b'C', 12, 2.406, -0.245, 0.941)
 (b'C', 12, 2.311, -0.359, -0.456) (b'C', 12, 1.042, -0.388, -1.058)
 (b'C', 12, -1.248, -0.099, 1.954) (b'C', 12, -1.288, 0.693, 3.11)
 (b'C', 12, -2.434, 0.786, 3.899) (b'C', 12, -3.583, 0.07, 3.539)
 (b'C', 12, -3.563, -0.728, 2.385) (b'C', 12, -2.417, -0.807, 1.61)
 (b'O', 16, -4.755, 0.081, 4.233) (b'C', 12, -4.849, 0.871, 5.418)
 (b'C', 12, -6.253, 0.694, 5.978) (b'C', 12, -6.478, 1.501, 7.263)
 (b'C', 12, -7.892, 1.324, 7.828) (b'C', 12, -8.114, 2.125, 9.104)
 (b'O', 16, -9.453, 1.885, 9.535) (b'C', 12, -9.9, 2.496, 10.668)
 (b'C', 12, -11.226, 2.214, 11.032) (b'C', 12, -11.774, 2.784, 12.17)
 (b'C', 12, -11.027, 3.656, 12.986) (b'C', 12, -9.706, 3.927, 12.605)
 (b'C', 12, -9.138, 3.36, 11.464) (b'C', 12, -11.617, 4.262, 14.203)
 (b'C', 12, -12.527, 3.546, 15.001) (b'C', 12, -13.084, 4.108, 16.143)
 (b'C', 12, -12.737, 5.415, 16.525) (b'C', 12,

## Creating arrays/6
* From the ndarray just built we can save a binary file with the ndarray data

* It can be read with np.fromfile

* Be careful when using np.fromfile w/ fortran binary files, you may need to deal with __field separators__...


In [54]:
arr.tofile('mol_bin') 
arr2 = np.fromfile('mol_bin', dtype=dt) 

In [55]:
%%bash
ls -lrt data

total 1452
-rw-r--r-- 1 mirko mirko    2745 May  5 12:26 mol.xyz
-rw-rw-r-- 1 mirko mirko 1478002 May  5 12:27 data.zip
drwxrwxr-x 2 mirko mirko    4096 May  5 12:28 stats


## Creating arrays/7

__(5)__ Special library functions (e.g. random, ...) or _ad hoc_ defined function

In [56]:
def func(i, j):
    return i*j+1

np.fromfunction(func, (3,4))   # meshgrid

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  3.,  5.,  7.]])

In [57]:
np.random.rand(4)

array([ 0.93054712,  0.6468215 ,  0.37944125,  0.39483142])

## ndarray attributes

Some useful ndarray attributes are: (let arr be the array)
* __`arr.dtype`__ &emsp; data-type object for this array
```python
a = np.ones(10); a.dtype
dtype('float64')
```
* __`arr.shape`__ &emsp; returns a tuple with the size of the array. Changing the tuple re-shapes the array
* __`arr.ndim`__ &emsp; number of dimension in array
* __`arr.size`__ &emsp; total number of elements


## (some) ndarray functions
Some useful ndarray functions are:
* __`arr.copy()`__ &emsp; returns a copy of the array
* __`arr.view()`__ &emsp; returns a new view of the array using the same data of arr (save memory space)
* __`arr.reshape()`__ &emsp; returns an array with a new shape
* __`arr.transpose()`__ &emsp; returns an array view with the shape transposed


## (some) ndarray functions/2
* __`arr.sum()`__


In [58]:
a = np.array([[1,4,2],[3,1,8]])
a.sum(axis=0)  # try also axis=None

array([ 4,  5, 10])

## (some) ndarray functions/3
```
>>> a = np.array([[1,1],[2,2]])
>>> a.sum(axis=0)
>>> array([ 3, 3])
```
![](files/images/sum.png)

## (some) ndarray functions/4
* __`arr.min|max()`__ &emsp; return min (or max) value
* __`arr.argmin|argmax()`__ &emsp; return the index of min (max) value
* __`arr.var|mean|std|prod()`__ &emsp; take the usual meaning


## (some) ndarray functions/5
__`sort`__ &emsp; array sorting
```python
>>> a = np.array([[1,4],[3,1]])
>>> np.sort(a)  # sort along the last axis
array([[1, 4],
[1, 3]])
>>> np.sort(a, axis=0)  # sort along x axis
array([[1, 1],
[3, 4]])
>>> np.sort(a, axis=None)  # sort the flattened# array
array([1, 1, 3, 4])
>>> np.sort(a, order=field)  # 'field' of a structured array 
```

## Basic routines overview
* Creating arrays routines (mentioned earlier in this presentation)
* Operation on two or more arrays (`dot, ...`)
* Shape functions (`split, resize, concatenate, stack`)
* Basic functions (`average, cov, vectorize,...`)
* Two-dimensional array functions (`eye, diag, ...`)  


## Indexing
* Indexing means selecting some of the array's values
* ndarrays can be indexed using the following syntax:
<center>`X[obj]`</center>

<center>`X[obj]`</center>
* Depending on __obj__, a different indexing is triggered:
 * __Basic slicing__ when __obj__ is an integer, or a tuple (or list) ofintegers, and slice objects.
   * always returns a __view__ of the array
 * __Record access__ when __obj__ is the string of a field of structured array
 * __Advanced selection__ when __obj__ contains a ndarray of data type integer or bool.
   * always returns a copy of the array

## Basic slicing/1
* A slice object is represented by X[__<span style="color:blue">I</span>:<span style="color:green">J</span>:<span style="color:red">K</span>__]
 * __I__ = __<span style="color:blue">first element</span>__ (included, default is 0)
 * __J__ = __<span style="color:green">last element</span>__ (excluded, default is length of the array)
 * __K__ = __<span style="color:red">step or stride </span>__ (default is 1)
 
* Slicing for ndarray works similarly to standard Python sequences but can be done over __multiple dimensions__


## Basic slicing/2
Examples: given a two dimensional __5x10__ ndarray “A”
* `A[3] = A[3,:] = A[3,::]` &emsp; represents the __4th__ row of the array (10 elements)
* `A[:,1] = A[::,1]` &emsp; represents the __2nd__ column of the array (5 elements)


## Basic slicing/3

![](files/images/slice.png)

## Basic slicing/4
* Ellipses (...) can be used to replace zero or more “:” terms so that the total number of dimensions in the slicing tuple matches the shape of the ndarray

In [59]:
a = np.arange(60) 
a.shape=(3,4,5) 
print(a[...,3])  # print a[:,:,3] → (3,4)
print('='*30)
print(a[1,...,3])  # print a[1,:,3] → (4)

[[ 3  8 13 18]
 [23 28 33 38]
 [43 48 53 58]]
[23 28 33 38]


## Exercise 3: Basic slicing
* Build a 2-dim array, then calculate all the average values along the rows for its odd and even columns.

![](files/images/slice_ex.png)

`hint: np.mean() or arr.mean()`

## Record access
* The fields of structured arrays can be accessed by indexing the array with string
```python
>>> ra
array([(b'H', 1), (b'C', 6)], 
      dtype=[('at', 'S3'), ('Z', '<i4')])
ra['at']   # array(['H', 'C'], dtype='|S3')
```

## Advanced selection
* Indexing arrays with other arrays
* This means `X[obj]` → `obj` is a `ndarray`
* There are two different ways:
 * __Boolean index arrays__. Involve giving a boolean array of the proper shape to indicate the values to be selected
 * __Integer index arrays__. Use one or more arrays of index values.


## Adv. selection: boolean index arrays
* ```python
  a = np.array([True, False, True])  # bool
  ```
* Boolean arrays must be of the (or _broadcastable_ to the) same shape of the array being indexed

In [60]:
y = np.arange(18).reshape(3,6)
b = y > 10
y[b]  # 1-d array

array([11, 12, 13, 14, 15, 16, 17])

## Exercise 4 ndarray selection
* From the atoms array calculate the contribution to the molecular weight for each of the different kind of atoms (C, N, H, O) making use of the Numpy selection

$$PM_c = \sum PA_c $$

Hint: use the advanced boolean section

## Exercise 4 ndarray selection
* Solution
```python
>>> arr[arr['symb']=='C']['PA'].sum()  # 372
>>> arr[arr['symb']=='H']['PA'].sum()  # 26
>>> arr[arr['symb']=='N']['PA'].sum()  # 28
>>> arr[arr['symb']=='O']['PA'].sum()  # 32
```

## ndarray selection
To summarize, selection:
* can save you __time__ (and code lines)
* enhances the code __performances__
 * avoid traversing array through python loops (internal (C) loops are still performed... more on that later)
* can save __memory__ (in place selection)
 


## NumPy (main) objects
NumPy provides two fundamental objects:
* __ndarray__;
* __ufunc__; functions that operate on one or more `ndarrays` __element-by-element__


## ufunc

## Universal functions/1
* Universal functions, ufuncs are functions that __operate__ on the `ndarray` objects 
* all `ufuncs` are instances of a general class, thus they behave the same. All `ufuncs` perform __element-by-element__ operations on the entire `ndarray(s)`
* These functions are __wrapper__ of some core functions, typically implemented in compiled (C or Fortran) code

## Universal functions/2

![](files/images/ufunc.png)

## Universal functions/3
* Ufunc loop may look something like
<pre style="font-size:50%;">
void ufunc_loop(void **args, int *dimensions, int *steps, void *data)
{
    /* int8 output = elementwise_function(int8 input_1, int8  
    * input_2)
    *
    * This function must compute the ufunc for many values at 
    * once, in the way shown below.
    */
    char *input_1 = (char*)args[0];
    char *input_2 = (char*)args[1];
    char *output = (char*)args[2];
    int i;
    for (i = 0; i < dimensions[0]; ++i) {
        *output = elementwise_function(*input_1, *input_2);
        input_1 += steps[0];
        input_2 += steps[1];
        output += steps[2];
    }
}
</pre>

## Universal functions/4

Examples:
```python
>>> a = np.array([a1,a2,...,an]) 
```
```python
>>> b = 1.5*a + 2   # * + / - all ufuncs 
```
* all the elements of “a” are multiplied by 1.5; result stored in a __temporary array__
* All the elements of the temp array are increased by 2; result stored in another __temporary array__
* b becomes a reference to the $2^{nd}$ temp array


## Universal functions (3)
* What happens when ufunc has to operate on two arrays of __different dimensions__?
* To be efficient, element-wise operations are required
* To operate element-by-element broadcasting is needed.


![](files/images/broadcasting1.png)

![](files/images/broadcasting2.png)

## Broadcasting/1
* Broadcasting allows to deal in a meaningful way with inputs that do not have the same shape.
* After having applied the broadcasting rules the shape of all arrays must match


## Broadcasting/2

Broadcasting follows these rules:

__1.__ Prepend 1 until all the arrays dimension matches

```
a.shape (2,2,3,6)  # a.ndim = 4  
b.shape (3,6)  # b.ndim = 2 

1 → b.ndim = 4
1 → b.shape (1,1,3,6)
```
 


__2.__  Arrays with a size of 1 along a particular dimension act like the array with the __largest size__ along that dimension.
 * The values of the array are assumed to be __the same along the broadcasted dimension__

## Broadcasting/3
* 1d-ndarrays are always broadcastable

```python
a.shape → (3)    b.shape -> (4,3);  
a.shape → (1,3)  # first rule, n. of dim matches
a.shape → (4,3)  # second rule
c = a*b 
c.shape → (4,3) # as expected  
```


```python
# another example
a.shape → (2,1,3)   
b.shape → (2,4,1);  
c = a*b c.shape → (2,4,3) # second rule

# Arrays not broadcastable
a.shape → (2,5,3)
b.shape → (2,4,1); 
c = a*b    # shape mismatch
```
 


## Broadcasting/4
* If needed it is possible to add a trailing dimension to the shape of a `ndarray`. This is a convenient way of taking the outer product (or any other outer operation) of two arrays
```python
a.shape → (3) b.shape → (4);  
c = a[:,np.newaxis]   # c.shape → (3,1)
c * b 
c.shape → (3,4)  
```

## Universal functions: performance
* Iterations over array should be avoided because they are not efficient. Performance using array arithmetics is better than using python loops.
 
* ~ 18x speedup (standard across NumPy)


In [61]:
# Using ufunc
x = np.arange(10**7)
%timeit y = x*3

The slowest run took 4.15 times longer than the fastest. This could mean that an intermediate result is being cached.
10 loops, best of 3: 18.3 ms per loop


In [62]:
# Using for loop
%timeit y = [x*3 for x in range(10**7)]

1 loop, best of 3: 1.01 s per loop


## Efficiency note
The operation
```python
>>> b = 2*a + 2
```
can be done with in-place operations
```python
>>> b = a  # b is a reference to a
>>> b *= 2
>>> b += 2
```
More efficient and doesn't require storing temp array

These operations affect array “a” as well; we can avoid this with
```python
>>> b = a.copy()
```

Other in-place operations
```python
>>> b += a >>> b *= a >>> b **= a
>>> b -= a
>>> b /= a
```

## Efficiency note/2:
* Let's consider the function
```python
>>> def myfunc(x): #  if x is an array
        if x<0:  #  x<0 becomes a bool array
            return 0
        else:  
            return sin(x)
```

* “if x<0” results in a boolean array and __cannot__ be evaluated by the if statement

## Efficiency note (3): Vectorization
We can vectorize our function using the function where
```python
>>> def vec_myfunc(x):
        y = np.where(x<0, 0, np.sin(x))
        return y  # now returns an array
```
`np.where`
```python
np.where(condition, x, y)  # condition → bool array  
                           # condition is true → x  
                           # condition is false → y 
```

## NumPy universal functions/1
* There are more than 60 ufuncs
* Some `ufuncs` are called automatically: i.e. np.multiply(x,y) is called internally when a*b is typed
* NumPy offers trigonometric functions, their inverse counterparts, and hyperbolic versions as well as the exponential and logarithmic functions. Here, a few examples:

```python
>>> b = np.sin(a)
>>> b = np.arcsin(a)
>>> b = np.sinh(a)
>>> b = a**2.5   # exponential
>>> b = np.log(a)
>>> b = np.exp(a)
>>> b = np.sqrt(a)
```

## NumPy universal functions/2
* Comparison functions: __greater, less, equal, logical_and/_or/_xor/_nor, maximum, minimum, ...__
```python
>>> a = np.array([2,0,3,5])
>>> b = np.array([1,1,1,6])
>>> np.maximum(a,b)
array([2, 1, 3, 6])
```
* Floating point functions:  __floor, ceil, isreal, iscomplex,...__


## Exercise 5 
![](files/images/inertia_t.png)

## Exercise 5: universal functions
* Calculate the molecular center of mass
$$
xcm=\frac{1}{MW}\sum_ix_i m_i \;\;\;\;\;\;\;  
ycm=\frac{1}{MW}\sum_iy_i m_i \;\;\;\:\;\;\; 
zcm=\frac{1}{MW}\sum_iz_i m_i
$$  
  

Calculate the moment of inertia tensor
$$ 
\left[ \begin{array}{ccc}
I_{11} & I_{12} & I_{13} \\
I_{21} & I_{22} & I_{23} \\
I_{31} & I_{32} & I_{33} \end{array} \right] 
$$
whose elemets can be calculated as:
$$
I_{11} = I_{xx} = \sum_i m_i(y_i^2+z_i^2) \;\;\;\;\;\;\;
I_{11} = I_{xx} = \sum_i m_i(y_i^2+z_i^2) \;\;\;\;\;\;\;
I_{11} = I_{xx} = \sum_i m_i(y_i^2+z_i^2) 
$$
$$
I_{12} = I_{xy} = -\sum_i m_ix_iy_i \;\;\;\;\;\;\;
I_{12} = I_{xy} = -\sum_i m_ix_iz_i \;\;\;\;\;\;\;
I_{12} = I_{xy} = -\sum_i m_iy_iz_i
$$

In [63]:
# molecular center of mass
MW = arr['PA'].sum() 
xcm = 1./MW * (arr['PA']*arr['x']).sum()
ycm = 1./MW * (arr['PA']*arr['y']).sum()
zcm = 1./MW * (arr['PA']*arr['z']).sum()
print(xcm,ycm,zcm)

-6.03111572052 1.86249781659 7.53604803493


In [64]:
# moment of inertia tensor
Ixx = (arr['PA']*(arr['y']**2 + arr['z']**2)).sum()
Iyy = (arr['PA']*(arr['x']**2 + arr['z']**2)).sum()
Izz = (arr['PA']*(arr['x']**2 + arr['y']**2)).sum()
Ixy = -(arr['PA']*arr['x']*arr['y']).sum()
Ixz = -(arr['PA']*arr['x']*arr['z']).sum()
Iyz = -(arr['PA']*arr['y']*arr['z']).sum()

TI = np.array([[Ixx, Ixy, Ixz],[Ixy, Iyy, Iyz], [Ixz, Iyz, Izz]])
print(TI)

[[ 47408.39735   10068.852991  35951.289303]
 [ 10068.852991  74181.085975 -12473.020517]
 [ 35951.289303 -12473.020517  34525.947869]]


##  Standard classes inheriting from ndarray


## Matrix objects/1
`Matrix` objects inherit from ndarray classes
* Matrix can be created using a Matlab-style notation
```python
>>> a = np.matrix('1 2; 3 4')
>>> print a
[[1 2]
 [3 4]]
```

* Matrix are always __two-dimensional__ objects
* Matrix objects over-ride multiplication to be __matrix-multiplication__, and over-ride power to be __matrix raised to a power__
* Matrix objects have higher __priority__ than ndarrays. Mixed operations result therefore in a matrix object  

## Matrix objects/2

* Matrix objects have special attributes:
 * `.T` &emsp; returns the transpose of the matrix
 * `.H` &emsp; returns the conjugate transpose of the matrix
 * `.I` &emsp; returns the inverse of the matrix
 * `.A` &emsp; returns a view of the data of the matrix as a 2-d array 


## Basic modules

## Basic modules: linear algebra/1

Contain functions to solve __linear systems__, finding the __inverse__, the __determinant__ of a matrix, and computing __eigenvalues__ and __eigenvectors__


In [65]:
# example

A = np.zeros((10,10)) # arrays initialization
x = np.arange(10)/2.0
for i in range(10):
    for j in range(10):
        A[i,j] = 2.0 + float(i+1)/float(j+i+1)
b = np.dot(A, x)
y = np.linalg.solve(A, b)  # A*y=b → y=x 
print(x)
print(y)
np.allclose(y,x, 10**-3)  # True, mind the tolerance! 

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5]
[  6.55458967e-09   4.99999617e-01   1.00000817e+00   1.49992553e+00
   2.00035593e+00   2.49901981e+00   3.00161072e+00   3.49844127e+00
   4.00081933e+00   4.49981962e+00]


True

## Basic modules: linear algebra/2
* Eigenvalues can also be computed:

```python
# eigenvalues only:
>>> A_eigenvalues = np.linalg.eigvals(A)

# eigenvalues and eigenvectors:
>>> A_eigenvalues, A_eigenvectors = np.linalg.eig(A)
```

## Exercise 6: matrices and linalg

1.  From the array TI of the last exercise build a matrix (__mTI__), calculate eigenvalues (__e__) and eigenvectors (__Ev__) and prove that: 
$$
Ev^T mTI \; Ev = 
\left[ \begin{array}{ccc}
e_1 & 0 & 0 \\
0 & e_2 & 0 \\
0 & 0 & e_3 \end{array} \right] 
$$

2. Now, for example, you can rotate all the atoms coordinates by multiplying them by the __Ev__ matrix

In [66]:
mTI = np.matrix(TI)
ev, Ev = np.linalg.eig(mTI)
print(ev)
Ev.T * mTI * Ev

[   936.24999268  77296.74540821  77882.43579311]


matrix([[  9.36249993e+02,  -9.59732294e-13,   4.97554775e-12],
        [ -2.82440737e-12,   7.72967454e+04,  -2.59691646e-09],
        [  4.59721150e-12,  -2.60149946e-09,   7.78824358e+04]])

## Basic modules: random numbers
* Calling the standard random module of Python in a loop to generate a sequence of random number is inefficient. Instead:

```python
>>> np.random.seed(100)
>>> x = np.random.random(4)
array([ 0.89132195, 0.20920212, 0.18532822,  
0.10837689])
>>> y = np.random.uniform(-1, 1, n)  # n uniform numbers in interval (-1,1)
``` 

* This module provides more general distributions like the normal distribution

```python
>>> mean = 0.0; stdev = 1.0
>>> u = np.random.normal(mean, stdev, n)
```

##  Exercise 7: random numbers
* Given a game in which you win back 10 times your bet if the sum of 4 dice is less than 10, determine (brute force, i.e. 1000000 trows) whether it is convenient to play the game or not

* hint: use `np.random.randint`

## Numpy: good to know

## Masked arrays (1)

```python
>>> x = np.arange(20).reshape(4,5)  # 2d array 
>>> x[2:,2:] = 2   # assignment
array([[ 0, 1, 2, 3, 4],
      [ 5, 6, 7, 8, 9],
      [10, 11, 2, 2, 2],
      [15, 16, 2, 2, 2]])
>>> x[x<5]  # x<5 bool array  
array([0, 1, 2, 3, 2, 2, 2, 2, 2, 2])  # 1d array
```

* What if we want to maintain the original shape of the array
* We can use masked arrays: the __shape of the array is kept__
* Invalid data can be flagged and ignored in math computations


In [67]:
x = np.arange(20).reshape(4,5)
x[2:,2:] = 2
import numpy.ma as ma
y = ma.masked_greater(x, 4)
y

masked_array(data =
 [[0 1 2 3 4]
 [-- -- -- -- --]
 [-- -- 2 2 2]
 [-- -- 2 2 2]],
             mask =
 [[False False False False False]
 [ True  True  True  True  True]
 [ True  True False False False]
 [ True  True False False False]],
       fill_value = 999999)

## Meshgrids/1
* Given a two-dimensional grid of points, namely $a_{i,j}=(x i , y j)$ we want to calculate for each point of the grid the values of a function $f(a_{ij})=f(x_i,y_j)$

* Suppose $f = \frac{x}{2} + y$

* $f$ is a `ufunc` (implicitly uses ufuncs: `add`, `divide`) so it operates element-by-element)

![](files/images/mesh.png)

In [68]:
# wrong
def f(x,y): 
    return x/2 + y

x = np.linspace(0,4,5)
y = x.copy()

values = f(x,y)
values

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

## Meshgrids/2


In [69]:
x = np.linspace(0,4,5)
y = x.copy()
xv,yv = np.meshgrid(x,y)
print(xv)
print(yv)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]
[[ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.]]


![](files/images/mesh2.png)

In [70]:
values=f(xv,yv)
values

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 2. ,  2.5,  3. ,  3.5,  4. ],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 4. ,  4.5,  5. ,  5.5,  6. ]])

## Bibliography
* http://docs.scipy.org/doc/
* Guide to NumPy (Travis E. Oliphant)
* NumPy User Guide
* Numpy Reference Guide
* Python Scripting for Computational Science (HansPetter Langtangen)
