
# Numpy 

multidimensional data array

In [ ]:
# Ipython magic
%pylab inline

In [23]:
## Equivalent to:
from numpy import *
from matplotlib import *

## Introduction

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

We can use the `numpy.array` function.

In [24]:
# a vector: the argument to the array function is a Python list
v = array([1,2,3,4])
v

array([1, 2, 3, 4])

In [25]:
# a matrix: the argument to the array function is a nested Python list
M = array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `numpy.ndarray`

In [26]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. 

We can check it with the `ndarray.shape` property.

In [27]:
v.shape

(4,)

In [28]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [29]:
M.size

4

Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [30]:
shape(M)

(2, 2)

In [31]:
size(M)

4

So far the `numpy.ndarray` looks awefully much like a Python list (or nested list). 

Why not simply use Python lists for computations instead of creating a new array type? 

**There are several reasons**

* Python lists are very general. 
    - They can contain any kind of object. 
    - They are dynamically typed. 
* They do not support mathematical functions 
    - such as matrix and dot multiplications, etc. 
    - Implementating such functions for Python lists would not be very efficient 
        * because of the dynamic typing

* Numpy arrays are **statically typed** and **homogeneous**. 
    - The type of the elements is determined when array is created
    - By already knowing the static type, numpy can implement low-level optimization
* Numpy arrays are memory efficient.
     - fast implementation of mathematical functions can be implemented in a compiled language
        * C and Fortran is used

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

In [32]:
M.dtype

dtype('int64')

We get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [33]:
M[0,0] = "hello"

ValueError: invalid literal for long() with base 10: 'hello'

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [34]:
M = array([[1, 2], [3, 4]], dtype=complex)

M

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Common types that can be used with `dtype` 

    `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the bit size of the data types

    `int64`, `int16`, `float128`, `complex128`.

## If i don't see it, i don't believe it

`ndarray` = n-dimension array

<img src="images/ndarray.png">

In [35]:
import numpy as np
dim = 10000

A quick benchmark

In [36]:
# Normal python vector
a = range(dim)
t1 = %timeit -o [i**2 for i in a]

1000 loops, best of 3: 655 µs per loop


In [37]:
# Numpy vector with normal python loop
b = np.arange(dim)
t2 = %timeit -o [i**2 for i in b]

1000 loops, best of 3: 1.61 ms per loop


In [38]:
# Numpy vector with numpy loop
c = np.arange(dim)
t3 = %timeit -n 1000 -o [c**2]

1000 loops, best of 3: 8.52 µs per loop


In [39]:
print "Python loops (no) speedup: ", t1.best / t2.best

Python loops (no) speedup:  0.406152553204


In [40]:
print "Numpy loops speedup:", int(t1.best / t3.best), "x"

Numpy loops speedup: 76 x


We want to make sure...

In [41]:
print "Type", type(a), [i**2 for i in a][0:10]

Type <type 'list'> [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [42]:
print type(b), (b**2)[0:10]

<type 'numpy.ndarray'> [ 0  1  4  9 16 25 36 49 64 81]


## Using more array-generating functions

#### arange

In [43]:
# create a range
x = arange(0, 10, 1) # arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x = arange(-1, 1, 0.1)
x

array([ -1.00000000e+00,  -9.00000000e-01,  -8.00000000e-01,
        -7.00000000e-01,  -6.00000000e-01,  -5.00000000e-01,
        -4.00000000e-01,  -3.00000000e-01,  -2.00000000e-01,
        -1.00000000e-01,  -2.22044605e-16,   1.00000000e-01,
         2.00000000e-01,   3.00000000e-01,   4.00000000e-01,
         5.00000000e-01,   6.00000000e-01,   7.00000000e-01,
         8.00000000e-01,   9.00000000e-01])

In [46]:
type(x)

numpy.ndarray

#### mgrid

In [50]:
print numpy.mgrid.__doc__.split('\n')[0]

`nd_grid` instance which returns a dense multi-dimensional "meshgrid".


In [47]:
x, y = mgrid[0:5, 0:5] # similar to meshgrid in MATLAB

In [48]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [49]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### random data

In [51]:
from numpy import random
# uniform random numbers in [0,1]
random.rand(5,5)

array([[ 0.45313647,  0.14142955,  0.77272655,  0.20367896,  0.32167228],
       [ 0.04176592,  0.60036747,  0.81355389,  0.47160333,  0.80524504],
       [ 0.00709146,  0.93860509,  0.09802889,  0.0159517 ,  0.98696721],
       [ 0.12565556,  0.10679347,  0.76733643,  0.75007393,  0.18243136],
       [ 0.28725657,  0.64479908,  0.98354907,  0.66431787,  0.17538844]])

In [52]:
# standard normal distributed random numbers
random.randn(5,5)

array([[ 0.5705737 , -1.33555098,  1.34980566, -0.17756223, -0.38634563],
       [ 1.57125823,  0.07848669,  0.37171167,  0.13390331,  0.41840155],
       [ 0.81951121, -1.25768302,  0.82470932, -0.41607539,  0.53312402],
       [ 1.68447583,  2.2662237 , -0.36930713,  0.46463003, -1.68883349],
       [-1.40038215, -1.98099268,  0.54778712,  0.66137473,  0.5446522 ]])

#### diag

In [53]:
# a diagonal matrix
diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [54]:
# diagonal with offset from the main diagonal
diag([1,2,3], k=1) 

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

#### zeros and ones

In [55]:
zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [56]:
ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

## File Input/Output

### Comma-separated values (CSV)

A very common file format for data files are the comma-separated values (CSV).

In [57]:
# To read data from such file into Numpy arrays we can use the `numpy.genfromtxt` function
?genfromtxt

In [58]:
# data source: https://archive.ics.uci.edu/ml/datasets/Covertype
A = genfromtxt('data/num.csv.gz', delimiter = ',')

In [59]:
A.shape

(71436, 55)

In [60]:
A.size

3928980

In [61]:
A[:4,:3]

array([[  2.59600000e+03,   5.10000000e+01,   3.00000000e+00],
       [  2.59000000e+03,   5.60000000e+01,   2.00000000e+00],
       [  2.80400000e+03,   1.39000000e+02,   9.00000000e+00],
       [  2.78500000e+03,   1.55000000e+02,   1.80000000e+01]])

Using `numpy.savetxt` we can store a Numpy array to a file in **TSV** format:

In [62]:
M = rand(3,3)

M

array([[ 0.93505276,  0.60056311,  0.6184588 ],
       [ 0.5394044 ,  0.03306618,  0.06320561],
       [ 0.96362526,  0.47756975,  0.70762126]])

In [63]:
savetxt("random-matrix.csv", M)

In [64]:
!cat random-matrix.csv

9.350527603125805554e-01 6.005631127707953265e-01 6.184588018140034782e-01
5.394043997203566976e-01 3.306617620488727649e-02 6.320560795323504344e-02
9.636252562118692300e-01 4.775697458346287450e-01 7.076212627587148418e-01


### Numpy's native file format

Useful when storing and reading back numpy array data. Use the functions `numpy.save` and `numpy.load`:

In [65]:
# numpy binary file saving
save("random-matrix.npy", M)
# check type of file
!file random-matrix.npy

random-matrix.npy: data


In [66]:
# very fast, but not portable
load("random-matrix.npy")

array([[ 0.93505276,  0.60056311,  0.6184588 ],
       [ 0.5394044 ,  0.03306618,  0.06320561],
       [ 0.96362526,  0.47756975,  0.70762126]])

## More properties of arrays

In [67]:
M.itemsize # bytes per element

8

In [68]:
M.nbytes # number of bytes

72

In [69]:
M.ndim # number of dimensions

2

In [70]:
# With `newaxis`, we can insert new dimensions in an array
v = array([1,2,3])
print "Original:", shape(v)

# column matrix
print "Col:", v[:,newaxis].shape

# row matrix
print "Row:", v[newaxis,:].shape


Original: (3,)
Col: (3, 1)
Row: (1, 3)


## Manipulating arrays

### Indexing

We can index elements in an array using the square bracket and indices:

In [71]:
# v is a vector, and has only one dimension, taking one index
v[0]

1

In [72]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M[1,1]

0.033066176204887276

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [73]:
M

array([[ 0.93505276,  0.60056311,  0.6184588 ],
       [ 0.5394044 ,  0.03306618,  0.06320561],
       [ 0.96362526,  0.47756975,  0.70762126]])

In [74]:
M[1]

array([ 0.5394044 ,  0.03306618,  0.06320561])

The same thing can be achieved with using `:` instead of an index

In [75]:
M[1,:] # row 1

array([ 0.5394044 ,  0.03306618,  0.06320561])

In [76]:
M[:,1] # column 1

array([ 0.60056311,  0.03306618,  0.47756975])

We can assign new values to elements in an array using indexing

In [77]:
M[0,0] = 1

In [78]:
M

array([[ 1.        ,  0.60056311,  0.6184588 ],
       [ 0.5394044 ,  0.03306618,  0.06320561],
       [ 0.96362526,  0.47756975,  0.70762126]])

In [79]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [80]:
M

array([[ 1.        ,  0.60056311, -1.        ],
       [ 0.        ,  0.        , -1.        ],
       [ 0.96362526,  0.47756975, -1.        ]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array

In [81]:
A = array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [82]:
A[1:3]

array([2, 3])

Array slices are *mutable*: 

if they are assigned a new value the original array from which the slice was extracted is modified

In [83]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [84]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [85]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [86]:
A[:3] # first three elements

array([ 1, -2, -3])

In [87]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [88]:
A = array([1,2,3,4,5])

In [89]:
A[-1] # the last element in the array

5

In [90]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [91]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [92]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [93]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

### Fancy indexing

Fancy indexing is the name for when **an array or list** is used in-place of an *index*

In [94]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [95]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

###We can also index masks
* e.g. a Numpy array of data type `bool`
    - an element is selected (True) or not (False) 
    - depending on the value of the index mask at the position each element

In [96]:
B = array([n for n in range(5)])
B

array([0, 1, 2, 3, 4])

In [97]:
row_mask = array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [98]:
# same thing
row_mask = array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [99]:
x = arange(0, 10, 0.5)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [103]:
mask = (5 < x) * (x < 7.5)
x[mask]
print mask
print x[mask]

[False False False False False False False False False False False  True
  True  True  True False False False False False]
[ 5.5  6.   6.5  7. ]


## Functions for extracting data from arrays and creating arrays

### where

The index mask can be converted to position index using the `where` function

In [104]:
indices = where(mask)

indices

(array([11, 12, 13, 14]),)

In [105]:
x[indices] # this indexing is equivalent to the fancy indexing x[mask]

array([ 5.5,  6. ,  6.5,  7. ])

### diag

With the diag function we can also extract the diagonal and subdiagonals of an array

In [106]:
diag(A)

array([ 0, 11, 22, 33, 44])

In [107]:
diag(A, -1)

array([10, 21, 32, 43])

### choose

Constructs an array by picking elements form several arrays

In [109]:
which = [1, 0, 1, 0]
choices = [[-2,-2,-2,-2], [5,5,5,5]]

choose(which, choices)

array([ 5, -2,  5, -2])

## Linear algebra

Efficient numerical calculation with Numpy

- Object should always be formulated in terms of matrix and vector operations
- like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [110]:
v1 = arange(0, 5)

In [111]:
v1 * 2

array([0, 2, 4, 6, 8])

In [112]:
v1 + 2

array([2, 3, 4, 5, 6])

In [113]:
# Also works on a matrix
A * 2, A + 2

(array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]), array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16],
        [22, 23, 24, 25, 26],
        [32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46]]))

### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [121]:
print A
print A * A # element-wise multiplication

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[[   0    1    4    9   16]
 [ 100  121  144  169  196]
 [ 400  441  484  529  576]
 [ 900  961 1024 1089 1156]
 [1600 1681 1764 1849 1936]]


In [122]:
v1 * v1

array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [116]:
A.shape, v1.shape

((5, 5), (5,))

In [117]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

### Matrix algebra

What about matrix mutiplication? 

* We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [118]:
dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [123]:
dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [124]:
dot(v1, v1)

30

Alternatively

* we can cast the array objects to the type `matrix`. 

<small>Note: This changes the behavior of the standard arithmetic operators `+, -, *` to use matrix algebra.</small>

In [130]:
M = matrix(A)
M

matrix([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44]])

In [129]:
v = matrix(v1).T # make it a column vector
v

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [131]:
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [132]:
M * v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

In [133]:
# inner product
v.T * v

matrix([[30]])

In [134]:
# with matrix objects, standard matrix algebra applies
v + M*v

matrix([[ 30],
        [131],
        [232],
        [333],
        [434]])

###warning
If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [135]:
v = matrix([1,2,3,4,5,6]).T

In [136]:
shape(M), shape(v)

((5, 5), (6, 1))

In [137]:
M * v

ValueError: shapes (5,5) and (6,1) not aligned: 5 (dim 1) != 6 (dim 0)

See also the related functions: `inner`, `outer`, `cross`, `kron`, `tensordot`

#FROM HERE

### Matrix computations

#### Inverse

In [ ]:
inv(C) # equivalent to C.I 

In [ ]:
C.I * C

#### Determinant

In [ ]:
det(C)

In [ ]:
det(C.I)

### Data processing

Often it is useful to store datasets in Numpy arrays. Numpy provides a number of functions to calculate statistics of datasets in arrays. 

For example, let's calculate some properties data from the Stockholm temperature dataset used above.

In [ ]:
# reminder, the tempeature dataset is stored in the data variable:
shape(data)

#### mean

In [ ]:
# the temperature data is in column 3
mean(data[:,3])

The daily mean temperature in Stockholm over the last 200 year so has been about 6.2 C.

#### standard deviations and variance

In [ ]:
std(data[:,3]), var(data[:,3])

#### min and max

In [ ]:
# lowest daily average temperature
data[:,3].min()

In [ ]:
# highest daily average temperature
data[:,3].max()

#### sum, prod, and trace

In [ ]:
d = arange(0, 10)
d

In [ ]:
# sum up all elements
sum(d)

In [ ]:
# product of all elements
prod(d+1)

In [ ]:
# cummulative sum
cumsum(d)

In [ ]:
# cummulative product
cumprod(d+1)

In [ ]:
# same as: diag(A).sum()
trace(A)

### Computations on subsets of arrays

We can compute with subsets of the data in an array using indexing, fancy indexing, and the other methods of extracting data from an array (described above).

For example, let's go back to the temperature dataset:

In [ ]:
!head -n 3 stockholm_td_adj.dat

The dataformat is: year, month, day, daily average temperature, low, high, location.

If we are interested in the average temperature only in a particular month, say February, then we can create a index mask and use the select out only the data for that month using:

In [ ]:
unique(data[:,1]) # the month column takes values from 1 to 12

In [ ]:
mask_feb = data[:,1] == 2

In [ ]:
# the temperature data is in column 3
mean(data[mask_feb,3])

With these tools we have very powerful data processing capabilities at our disposal. For example, to extract the average monthly average temperatures for each month of the year only takes a few lines of code: 

In [ ]:
months = arange(1,13)
monthly_mean = [mean(data[data[:,1] == month, 3]) for month in months]

fig, ax = subplots()
ax.bar(months, monthly_mean)
ax.set_xlabel("Month")
ax.set_ylabel("Monthly avg. temp.");

### Calculations with higher-dimensional data

When functions such as `min`, `max`, etc., is applied to a multidimensional arrays, it is sometimes useful to apply the calculation to the entire array, and sometimes only on a row or column basis. Using the `axis` argument we can specify how these functions should behave: 

In [ ]:
m = rand(3,3)
m

In [ ]:
# global max
m.max()

In [ ]:
# max in each column
m.max(axis=0)

In [ ]:
# max in each row
m.max(axis=1)

Many other functions and methods in the `array` and `matrix` classes accept the same (optional) `axis` keyword argument.

## Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays.

In [ ]:
A

In [ ]:
n, m = A.shape

In [ ]:
B = A.reshape((1,n*m))
B

In [ ]:
B[0,0:5] = 5 # modify the array

B

In [ ]:
A # and the original variable is also changed. B is only a different view of the same data

We can also use the function `flatten` to make a higher-dimensional array into a vector. But this function create a copy of the data.

In [ ]:
B = A.flatten()

B

In [ ]:
B[0:5] = 10

B

In [ ]:
A # now A has not changed, because B's data is a copy of A's, not refering to the same data

## Stacking and repeating arrays

Using function `repeat`, `tile`, `vstack`, `hstack`, and `concatenate` we can create larger vectors and matrices from smaller ones:

### tile and repeat

In [ ]:
a = array([[1, 2], [3, 4]])

In [ ]:
# repeat each element 3 times
repeat(a, 3)

In [ ]:
# tile the matrix 3 times 
tile(a, 3)

### concatenate

In [ ]:
b = array([[5, 6]])

In [ ]:
concatenate((a, b), axis=0)

In [ ]:
concatenate((a, b.T), axis=1)

### hstack and vstack

In [ ]:
vstack((a,b))

In [ ]:
hstack((a,b.T))

## Copy and "deep copy"

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (techincal term: pass by reference). 

In [ ]:
A = array([[1, 2], [3, 4]])

A

In [ ]:
# now B is referring to the same array data as A 
B = A 

In [ ]:
# changing B affects A
B[0,0] = 10

B

In [ ]:
A

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to do a so-called "deep copy" using the function `copy`:

In [ ]:
B = copy(A)

In [ ]:
# now, if we modify B, A is not affected
B[0,0] = -5

B

In [ ]:
A

## Iterating over array elements

Generally, we want to avoid iterating over the elements of arrays whenever we can (at all costs). The reason is that in a interpreted language like Python (or MATLAB), iterations are really slow compared to vectorized operations. 

However, sometimes iterations are unavoidable. For such cases, the Python `for` loop is the most convenient way to iterate over an array:

In [ ]:
v = array([1,2,3,4])

for element in v:
    print(element)

In [ ]:
M = array([[1,2], [3,4]])

for row in M:
    print("row", row)
    
    for element in row:
        print(element)

When we need to iterate over each element of an array and modify its elements, it is convenient to use the `enumerate` function to obtain both the element and its index in the `for` loop: 

In [ ]:
for row_idx, row in enumerate(M):
    print("row_idx", row_idx, "row", row)
    
    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)
       
        # update the matrix M: square each element
        M[row_idx, col_idx] = element ** 2

In [ ]:
# each element in M is now squared
M

## Using arrays in conditions

When using arrays in conditions in for example `if` statements and other boolean expressions, one need to use one of `any` or `all`, which requires that any or all elements in the array evalutes to `True`:

In [ ]:
M

In [ ]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

In [ ]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

## Type casting

Since Numpy arrays are *statically typed*, the type of an array does not change once created. But we can explicitly cast an array of some type to another using the `astype` functions (see also the similar `asarray` function). This always create a new array of new type:

In [ ]:
M.dtype

In [ ]:
M2 = M.astype(float)

M2

In [ ]:
M2.dtype

In [ ]:
M3 = M.astype(bool)

M3

## Versions

In [22]:
%reload_ext version_information

%version_information numpy

Software versions
Python 2.7.9 64bit [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
IPython 3.1.0
OS Linux 4.0.3 boot2docker x86_64 with debian jessie sid
numpy 1.9.2
Fri Jun 05 19:55:09 2015 UTC