In [24]:
import numpy as np

a = np.ones((4, 4), dtype=int)
a[3,1] = 6
a[2,3] = 2

b = np.zeros((6, 5))
b[1:] = np.diag(np.arange(2, 7))

print(a)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 6 1 1]]
[[ 0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.]
 [ 0.  3.  0.  0.  0.]
 [ 0.  0.  4.  0.  0.]
 [ 0.  0.  0.  5.  0.]
 [ 0.  0.  0.  0.  6.]]


In [26]:
block = np.array([[4, 3], [2, 1]])
a = np.tile(block, (2, 3))

print(a)

[[4 3 4 3 4 3]
 [2 1 2 1 2 1]
 [4 3 4 3 4 3]
 [2 1 2 1 2 1]]


In [27]:
a = np.arange(10)

b = np.arange(5)

a[5:] = b[::-1]

print(a)


[0 1 2 3 4 4 3 2 1 0]


In [28]:
a = np.arange(1, 16).reshape(3, -1).T
print(a)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [29]:
is_prime = np.ones((100,), dtype=bool)
is_prime[:2] = 0
N_max = int(np.sqrt(len(is_prime)))
for j in range(2, N_max):
    if is_prime[j]: 
        is_prime[j*j::j] = False
print([i for i in range(100) if is_prime[i]])

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [30]:
a=np.arange(3)
b=np.zeros(10)
a
b[[0,4,5]]=a
b

array([ 0.,  0.,  0.,  0.,  1.,  2.,  0.,  0.,  0.,  0.])